apiVersion: apps/v1
kind: Deployment
metadata:
  name: neo4j-deployment
  labels: 
    app: app-neo4j
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pod-neo4j
  template:
    metadata:
      labels:
        app: pod-neo4j
    spec:
      containers:
      - name: neo4j
        image: neo4j
        ports:
        - containerPort: 7474 
          containerPort: 7687 


---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service
spec:
  type: LoadBalancer
  selector:
    app: pod-neo4j
  ports:
    - protocol: TCP
      port: 7474 
      targetPort: 7474 
      nodePort: 30002

---
apiVersion: v1
kind: Service
metadata:
  name: neo4j-service2
spec:
  type: LoadBalancer
  selector:
    app: pod-neo4j
  ports:
    - protocol: TCP
      port: 7687 
      targetPort: 7687 
      nodePort: 30003


